rev: new header pict

diff --git a/Dockerfile.local b/Dockerfile.local
--- a/Dockerfile.local
+++ b/Dockerfile.local
@@ -1,9 +1,8 @@
 ##### DEPENDENCIES
 
-FROM --platform=linux/amd64 node:18-alpine3.17 AS deps
+FROM --platform=linux/amd64 node:16-alpine3.17 AS deps
 RUN apk add --no-cache libc6-compat openssl1.1-compat
 WORKDIR /app
-RUN ls
 
 # Install Prisma Client - remove if not using Prisma
 
@@ -14,7 +13,6 @@ COPY prisma ./
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
 
 # Copy Google Secret Credentials
-
 # COPY secret ./
 
 RUN \
@@ -26,14 +24,20 @@ RUN \
 
 ##### BUILDER
 
-FROM --platform=linux/amd64 node:18-alpine3.17 AS builder
+FROM --platform=linux/amd64 node:16-alpine3.17 AS builder
 ARG DATABASE_URL
 ARG NEXT_PUBLIC_CLIENTVAR
 WORKDIR /app
-COPY --from=deps ./node_modules /app/node_modules
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
 # ENV NEXT_TELEMETRY_DISABLED 1
+RUN \
+  if [ -f yarn.lock ]; then yarn install --only=production; \
+  elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm install --only=production; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && SKIP_ENV_VALIDATION=1 pnpm install --only=production; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 RUN \
   if [ -f yarn.lock ]; then yarn build; \
@@ -42,9 +46,11 @@ RUN \
   else echo "Lockfile not found." && exit 1; \
   fi
 
+
+
 ##### RUNNER
 
-FROM --platform=linux/amd64 node:18-alpine3.17 AS runner
+FROM --platform=linux/amd64 node:16-alpine3.17 AS runner
 WORKDIR /app
 ENV NODE_ENV production 
 
@@ -58,8 +64,10 @@ COPY --from=builder /app/public ./public
 COPY --from=builder /app/package.json ./package.json
 # COPY --from=builder /app/secret ./secret
 
-COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
-COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
+COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
 USER nextjs
 EXPOSE 3000
